// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluZn8aaBPdwZtrXCilbTJtE7NqwiAwv4',
    appId: '1:404431621277:web:c09b8f7f1e07a4f69f5874',
    messagingSenderId: '404431621277',
    projectId: 'fir-flutter-codelab-b7161',
    authDomain: 'fir-flutter-codelab-b7161.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b7161.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi6V2JwLjWTcmt_tAOpeQsRdYLNCOfn68',
    appId: '1:404431621277:android:62361e3883c2f59c9f5874',
    messagingSenderId: '404431621277',
    projectId: 'fir-flutter-codelab-b7161',
    storageBucket: 'fir-flutter-codelab-b7161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXWLlzoukb7DmSVVi_HtE1ZhCzFK2XGM',
    appId: '1:404431621277:ios:64312b96f73d733e9f5874',
    messagingSenderId: '404431621277',
    projectId: 'fir-flutter-codelab-b7161',
    storageBucket: 'fir-flutter-codelab-b7161.appspot.com',
    iosClientId: '404431621277-v41spq6g9nuv6t7qhphgpaflsahc5mpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBXWLlzoukb7DmSVVi_HtE1ZhCzFK2XGM',
    appId: '1:404431621277:ios:64312b96f73d733e9f5874',
    messagingSenderId: '404431621277',
    projectId: 'fir-flutter-codelab-b7161',
    storageBucket: 'fir-flutter-codelab-b7161.appspot.com',
    iosClientId: '404431621277-v41spq6g9nuv6t7qhphgpaflsahc5mpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
